name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.0
  intl: 0.19.0

dev_dependencies:
  http: ^1.2.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # uses-material-design: true

  assets: 
    - assets/
